# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-15 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrape_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('date', models.DateTimeField()),
                ('home_elo', models.IntegerField(default=0)),
                ('away_elo', models.IntegerField(default=0)),
                ('elo_applied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dk_salary', models.IntegerField(blank=True, null=True)),
                ('minutes', models.IntegerField()),
                ('offensive_rebounds', models.IntegerField()),
                ('defensive_rebounds', models.IntegerField()),
                ('personal_fouls', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('steals', models.IntegerField()),
                ('blocks', models.IntegerField()),
                ('turnovers', models.IntegerField()),
                ('free_throws_made', models.IntegerField()),
                ('free_throws_attempted', models.IntegerField()),
                ('twos_made', models.IntegerField()),
                ('twos_attempted', models.IntegerField()),
                ('threes_made', models.IntegerField()),
                ('threes_attempted', models.IntegerField()),
                ('field_goals_made', models.IntegerField()),
                ('field_goals_attempted', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrape_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('position', models.CharField(blank=True, max_length=2, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('games_started', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('14', '14-15'), ('15', '15-16'), ('16', '16-17')], max_length=2)),
                ('scrape_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrape_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('city', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('abbreviation', models.CharField(max_length=4, unique=True)),
                ('elo', models.IntegerField(default=1500)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='current_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='basketball.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='games',
            field=models.ManyToManyField(through='basketball.GameLog', to='basketball.Game'),
        ),
        migrations.AddField(
            model_name='gamelog',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball.Player'),
        ),
        migrations.AddField(
            model_name='gamelog',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='basketball.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='basketball.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='basketball.Season'),
        ),
    ]
