# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-18 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('entree_fee', models.DecimalField(decimal_places=2, max_digits=16)),
                ('entries', models.IntegerField()),
                ('total_entries', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContestPayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball.Contest')),
            ],
        ),
    ]
