# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-18 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0002_contest_contestpayout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='entree_fee',
            new_name='entry_fee',
        ),
    ]
